name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install afdko
      run: pip3 install afdko
    - name: Begin
      run: python3 ./build/buildstatic.py

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-01"
        artifacts: |
          *.zip
          *.7z
        allowUpdates: true
        prerelease: true
        draft: true
        name: "Build Test"
        body: "Shanggu"

    - uses: actions/upload-artifact@v4
      with:
        name: ShangguStatic
        path: |
          *.7z
          *.zip

  buildvf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install afdko
      run: pip3 install afdko
    - name: Begin
      run: python3 ./build/buildvf.py

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-01"
        artifacts: "*.7z"
        allowUpdates: true
        prerelease: true
        draft: true
        name: "Build Test"
        body: "Shanggu"

    - uses: actions/upload-artifact@v4
      with:
        name: ShangguVF
        path: "*.7z"

