name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install afdko
      run: pip3 install afdko
    - run: chmod +x ./main/otfcc/*

    - name: Build
      run: python3 ./build/buildstatic.py

    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: python3 ./build/upload.py

    - uses: actions/upload-artifact@v4
      with:
        name: ShangguStatic
        path: |
          *.7z
          *.zip

  buildvf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install afdko
      run: pip3 install afdko

    - name: Build
      run: python3 ./build/buildvf.py

    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: python3 ./build/upload.py

    - uses: actions/upload-artifact@v4
      with:
        name: ShangguVF
        path: "*.7z"

