name: Build ttf

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Begin
      run: |
        sudo apt install wine
        python3 ./buildttf.py
    - uses: actions/upload-artifact@v3
      with:
        name: AdvocateAncientTTFs
        path: "*.7z"

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-ttf-01"
        artifacts: "*.7z"
        allowUpdates: true
        draft: true
        name: "Build Test"
        body: "Advocate Ancient TTF"
