name: Build serif ttf

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Begin
      run: |
        pip3 install afdko
        python3 ./build-serif-ttf.py
    - uses: actions/upload-artifact@v3
      with:
        name: AdvocateAncientSerif
        path: "*.7z"

    - name: Upload to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "test-ttfserif-001"
        prerelease: true
        draft: true
        title: Build Test
        files: |
            *.7z
