
name: Build

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Begin
      run: |
        python3 ./build.py
    - uses: actions/upload-artifact@v3
      with:
        name: out
        path: "*.7z"

    - name: Upload to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "test-release-AA"
        prerelease: true
#         draft: true
        title: Build Test
        files: |
            *.7z
